/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.atividade3.gui;

import br.com.senac.atividade3.persistencia.JPAUtil;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import jakarta.persistence.TypedQuery;
import java.util.List;

/**
 *
 * @author Renato Rodrigues
 */
public class TelaSala extends javax.swing.JFrame {

    /**
     * Creates new form TelaSala
     */
    public TelaSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBFilme1 = new javax.swing.JComboBox<>();
        CBFilme2 = new javax.swing.JComboBox<>();
        CBFilme3 = new javax.swing.JComboBox<>();
        CBFilme4 = new javax.swing.JComboBox<>();
        CBFilme5 = new javax.swing.JComboBox<>();
        CBFilme6 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        CBHorario1 = new javax.swing.JComboBox<>();
        CBHorario2 = new javax.swing.JComboBox<>();
        CBHorario3 = new javax.swing.JComboBox<>();
        CBHorario4 = new javax.swing.JComboBox<>();
        CBHorario5 = new javax.swing.JComboBox<>();
        CBHorario6 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Você vai aqui! E você... ali!");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Sala 1:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sala 2:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Sala 3:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Sala 4:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Sala 5:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Sala 6:");

        CBFilme1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBFilme1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBFilme2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBFilme2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBFilme3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBFilme3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBFilme4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBFilme4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBFilme5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBFilme5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBFilme6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBFilme6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Designe os filmes às salas e horários.");

        btnVoltar.setText("< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        CBHorario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBHorario1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "15:00", "20:00" }));

        CBHorario2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBHorario2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "15:00", "20:00" }));

        CBHorario3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBHorario3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "15:00", "20:00" }));

        CBHorario4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBHorario4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "15:00", "20:00" }));

        CBHorario5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBHorario5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "14:00", "18:00", "22:00" }));

        CBHorario6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBHorario6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15:00", "20:00" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addComponent(jLabel5))
                            .addComponent(jLabel6))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBFilme5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFilme4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFilme3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFilme6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFilme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFilme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHorario6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHorario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHorario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHorario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBFilme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBFilme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBFilme3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBHorario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBFilme4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBHorario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBFilme5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBHorario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBFilme6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBHorario6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    EntityManager em = JPAUtil.getEntityManager();
    
    try {
        TypedQuery<String> query = em.createQuery("SELECT titulo FROM Filmes WHERE status = 'Aberto' OR status = 'Em cartaz'", String.class);
        List<String> titulos = query.getResultList();
        
        CBFilme1.removeAllItems(); CBFilme1.addItem(""); CBFilme1.setSelectedIndex(0);
        CBFilme2.removeAllItems(); CBFilme2.addItem(""); CBFilme2.setSelectedIndex(0);
        CBFilme3.removeAllItems(); CBFilme3.addItem(""); CBFilme3.setSelectedIndex(0);
        CBFilme4.removeAllItems(); CBFilme4.addItem(""); CBFilme4.setSelectedIndex(0);
        CBFilme5.removeAllItems(); CBFilme5.addItem(""); CBFilme5.setSelectedIndex(0);
        CBFilme6.removeAllItems(); CBFilme6.addItem(""); CBFilme6.setSelectedIndex(0);  
        
        for (String titulo : titulos) {
        CBFilme1.addItem(titulo); CBFilme2.addItem(titulo);
        CBFilme3.addItem(titulo); CBFilme4.addItem(titulo);
        CBFilme5.addItem(titulo); CBFilme6.addItem(titulo);
        }
      em.getTransaction().begin();
      TypedQuery<Integer> queri = em.createQuery("SELECT s.id FROM Salas s WHERE s.id_filmes IS NOT NULL", Integer.class); 
      List<Integer> resultados = queri.getResultList();
      em.getTransaction().commit();
      for (int valor : resultados) {
        switch (valor) { 
         case 1: CBFilme1.setEnabled(false); CBHorario1.setEnabled(false); CBFilme1.setSelectedIndex(1); break;
         case 2: CBFilme2.setEnabled(false); CBHorario2.setEnabled(false); CBFilme2.setSelectedIndex(1); break;
         case 3: CBFilme3.setEnabled(false); CBHorario3.setEnabled(false); CBFilme3.setSelectedIndex(1); break;
         case 4: CBFilme4.setEnabled(false); CBHorario4.setEnabled(false); CBFilme4.setSelectedIndex(1); break;
         case 5: CBFilme5.setEnabled(false); CBHorario5.setEnabled(false); CBFilme5.setSelectedIndex(1); break;
         case 6: CBFilme6.setEnabled(false); CBHorario6.setEnabled(false); CBFilme6.setSelectedIndex(1); break;
        }
      }
      
    } finally { em.close(); }
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        EntityManager em = JPAUtil.getEntityManager();
        if (!CBFilme1.getSelectedItem().toString().trim().equals("") && CBFilme1.isEnabled()) { em.getTransaction().begin(); String sql = "SELECT id FROM Filmes WHERE titulo = :titulo"; TypedQuery<Integer> query = em.createQuery(sql, Integer.class); query.setParameter("titulo", CBFilme1.getSelectedItem().toString());  int rs = query.getSingleResult();  em.getTransaction().commit();
        em.getTransaction().begin(); String sql3 = "UPDATE Filmes SET status = :status WHERE id = :id"; Query query3 = em.createNativeQuery(sql3); query3.setParameter("status", "Em cartaz"); query3.setParameter("id", rs); query3.executeUpdate(); em.getTransaction().commit();
        em.getTransaction().begin(); String sql2 = "UPDATE Salas SET id_filmes = :id, horarios = :horario WHERE id = 1"; Query query2 = em.createNativeQuery(sql2); query2.setParameter("id", rs); query2.setParameter("horario", CBHorario1.getSelectedItem().toString()); query2.executeUpdate(); em.getTransaction().commit();  }
       
        if (!CBFilme2.getSelectedItem().toString().trim().equals("") && CBFilme2.isEnabled()) { em.getTransaction().begin(); String sql = "SELECT id FROM Filmes WHERE titulo = :titulo"; TypedQuery<Integer> query = em.createQuery(sql, Integer.class); query.setParameter("titulo", CBFilme2.getSelectedItem().toString());  int rs = query.getSingleResult();  em.getTransaction().commit();
        em.getTransaction().begin(); String sql3 = "UPDATE Filmes SET status = :status WHERE id = :id"; Query query3 = em.createNativeQuery(sql3); query3.setParameter("status", "Em cartaz"); query3.setParameter("id", rs); query3.executeUpdate(); em.getTransaction().commit();
        em.getTransaction().begin(); String sql2 = "UPDATE Salas SET id_filmes = :id, horarios = :horario WHERE id = 2"; Query query2 = em.createNativeQuery(sql2); query2.setParameter("id", rs); query2.setParameter("horario", CBHorario2.getSelectedItem().toString()); query2.executeUpdate(); em.getTransaction().commit();}
        
        if (!CBFilme3.getSelectedItem().toString().trim().equals("") && CBFilme3.isEnabled()) { em.getTransaction().begin(); String sql = "SELECT id FROM Filmes WHERE titulo = :titulo"; TypedQuery<Integer> query = em.createQuery(sql, Integer.class); query.setParameter("titulo", CBFilme3.getSelectedItem().toString());  int rs = query.getSingleResult();  em.getTransaction().commit();
        em.getTransaction().begin(); String sql3 = "UPDATE Filmes SET status = :status WHERE id = :id"; Query query3 = em.createNativeQuery(sql3); query3.setParameter("status", "Em cartaz"); query3.setParameter("id", rs); query3.executeUpdate(); em.getTransaction().commit();
        em.getTransaction().begin(); String sql2 = "UPDATE Salas SET id_filmes = :id, horarios = :horario WHERE id = 3"; Query query2 = em.createNativeQuery(sql2); query2.setParameter("id", rs); query2.setParameter("horario", CBHorario3.getSelectedItem().toString()); query2.executeUpdate(); em.getTransaction().commit();}
        
        if (!CBFilme4.getSelectedItem().toString().trim().equals("") && CBFilme4.isEnabled()) { em.getTransaction().begin(); String sql = "SELECT id FROM Filmes WHERE titulo = :titulo"; TypedQuery<Integer> query = em.createQuery(sql, Integer.class); query.setParameter("titulo", CBFilme4.getSelectedItem().toString());  int rs = query.getSingleResult();  em.getTransaction().commit();
        em.getTransaction().begin(); String sql3 = "UPDATE Filmes SET status = :status WHERE id = :id"; Query query3 = em.createNativeQuery(sql3); query3.setParameter("status", "Em cartaz"); query3.setParameter("id", rs); query3.executeUpdate(); em.getTransaction().commit();
        em.getTransaction().begin(); String sql2 = "UPDATE Salas SET id_filmes = :id, horarios = :horario WHERE id = 4"; Query query2 = em.createNativeQuery(sql2); query2.setParameter("id", rs); query2.setParameter("horario", CBHorario4.getSelectedItem().toString()); query2.executeUpdate(); em.getTransaction().commit();}
       
        if (!CBFilme5.getSelectedItem().toString().trim().equals("") && CBFilme5.isEnabled()) { em.getTransaction().begin(); String sql = "SELECT id FROM Filmes WHERE titulo = :titulo"; TypedQuery<Integer> query = em.createQuery(sql, Integer.class); query.setParameter("titulo", CBFilme5.getSelectedItem().toString());  int rs = query.getSingleResult();  em.getTransaction().commit();
        em.getTransaction().begin(); String sql3 = "UPDATE Filmes SET status = :status WHERE id = :id"; Query query3 = em.createNativeQuery(sql3); query3.setParameter("status", "Em cartaz"); query3.setParameter("id", rs); query3.executeUpdate(); em.getTransaction().commit();
        em.getTransaction().begin(); String sql2 = "UPDATE Salas SET id_filmes = :id, horarios = :horario WHERE id = 5"; Query query2 = em.createNativeQuery(sql2); query2.setParameter("id", rs); query2.setParameter("horario", CBHorario5.getSelectedItem().toString()); query2.executeUpdate(); em.getTransaction().commit();}
       
        if (!CBFilme6.getSelectedItem().toString().trim().equals("") && CBFilme6.isEnabled()) { em.getTransaction().begin(); String sql = "SELECT id FROM Filmes WHERE titulo = :titulo"; TypedQuery<Integer> query = em.createQuery(sql, Integer.class); query.setParameter("titulo", CBFilme6.getSelectedItem().toString());  int rs = query.getSingleResult();  em.getTransaction().commit();
        em.getTransaction().begin(); String sql3 = "UPDATE Filmes SET status = :status WHERE id = :id"; Query query3 = em.createNativeQuery(sql3); query3.setParameter("status", "Em cartaz"); query3.setParameter("id", rs); query3.executeUpdate(); em.getTransaction().commit();
        em.getTransaction().begin(); String sql2 = "UPDATE Salas SET id_filmes = :id, horarios = :horario WHERE id = 6"; Query query2 = em.createNativeQuery(sql2); query2.setParameter("id", rs); query2.setParameter("horario", CBHorario6.getSelectedItem().toString()); query2.executeUpdate(); em.getTransaction().commit();}
        
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBFilme1;
    private javax.swing.JComboBox<String> CBFilme2;
    private javax.swing.JComboBox<String> CBFilme3;
    private javax.swing.JComboBox<String> CBFilme4;
    private javax.swing.JComboBox<String> CBFilme5;
    private javax.swing.JComboBox<String> CBFilme6;
    private javax.swing.JComboBox<String> CBHorario1;
    private javax.swing.JComboBox<String> CBHorario2;
    private javax.swing.JComboBox<String> CBHorario3;
    private javax.swing.JComboBox<String> CBHorario4;
    private javax.swing.JComboBox<String> CBHorario5;
    private javax.swing.JComboBox<String> CBHorario6;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
